train:
  batch_size: 256
  epochs_stage0: 5
  epochs_stage1: 20
  lr_backbone: 1e-5
  lr_heads: 1e-4
model:
  dim_descriptor: 256
  subgrid: 2 # 2×2
  freeze_backbone_stage1: true
data:
  img_size: [224, 224]    # H, W
  patch_size: 14          # ViT S/14
  synthetic_len: 30000
  synthetic_root: data/synthetic_shapes
  coco_root: data/train2017
  num_workers: 14